spring:
  web:
    resources:
  #     static-locations:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    contentnegotiation:
      favor-parameter: true
#    static-path-pattern: /res/**

