GET http://localhost:8080/user
Accept: application/json
Cache-Control: no-cache

<> 2021-07-13T091412.200.json

###

GET http://localhost:8080/user
Accept: application/xml
Cache-Control: no-cache

<> 2021-07-13T091408.200.xml

###

GET http://localhost:8080/user?format=json
Accept: application/xml
Cache-Control: no-cache

###

GET http://localhost:8080/xml
Accept: application/ac
Cache-Control: no-cache

###

GET http://localhost:8080/xml
Accept: application/json
Cache-Control: no-cache

###
